sudo: false
language: java
notifications:
  email: false
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
before_install: wget https://gist.githubusercontent.com/Doridian/01cb63301fe4d022f533bd221e227970/raw/0771d2c50808b295abfbabe266be7368c3273974/settings.xml
  -O settings.bin
script: mvn deploy -DaltDeploymentRepository=deployment-repo-id::default::https://maven.doridian.net/repository/maven-snapshots/
  --settings settings.bin
env:
  global:
  - secure: fa12YcL4kMBWSSwRSqOhhR/NVL8Qvw2TNVqhsOGMs/COZM2R+WG4ninQIYALqlu5/Q85ddoFkLEaMHm44FaK7nIuRYA+zrhkvspCkl5H3zO98EFC9xZoyyiqw3hhLSBeDF/kVVWGnz+vVxuTzfntFNDF/0PTGxdBtaO1l0HAL5w9Gc1fLOHQ8/zqS69258T9L4+jaRFvOVenQQpbKSyP/Bwi73B+g+SQScNJsdc+t73ujwpgnh++PzCJ3cEt9Rse8L/ZBH1VqGgJ2b+vemEz62uJXF4GRu6Cjl1EQGFFKSrn8QNsgKEoIWDPDkjSg0uAVBjS3b7RYy/7FKCzkirOoJuaDtRn+Oph/sCvyfvUb63rRp129xXhVVwBTTsosc7Yzr6F+F8/yA2ESJ9xcn2i3Co2B7091bvP4Zi4O8+3ga4CPWjZOAglkyvqEtSvMOFjDOPaMCZKaNn6g2zNBiaeuxEpSq2HTZVt7Ew+yCvHaxDxM/MQRG1EKPRP/U+IcSzor8saeQoC95ZfQnCl8d1CWfBh/2GxcrZEoVDpFTmXVT0RJidQRnrRjAlVfvo3auCSMSaiKUPxx97mAcHlOPJJKcqKBADk5Ravu4QkeND3/AMqhm4ezZsyfKjkx6HNIlqkHenlrmRtFpnQ62RNXekiBczA1jg7UnvdJLL9q0hEk1I=
  - secure: km1C0T0A5wGjNEcB1FS/st58Bx99bh3XdWU9F9BxVSkkd9Jdjt2WerWkPKjGIGFAiPm29dCVsDxafU1a7rdmgd65hDH2uWsJcnJmmelVIvXwPN7GDwsh0SHffJLTzKfdr/hTmXwX6o5K9YltUxcF7Y1Jbf8hMIqGIuoHnxrWFt605p0fsZtm9MZZV0Fb+4cyOyAJE2ZMfPwk6BmPl4iMDDv8PyLvoEupNcmXCDXrS2CH/jffHqNZHi3ySSI2DTLdFKH0goHTnSFv4A3+t+cerZDCqBLG8rjzmxB7FORuuRdSVRlGZNOvnngltlCheTnz+9zblHH2r8Sg9jQmRyeYnS3aCI+8EpY1g5f+sYOPflJ5JOrU2QwXnPqdCKdPk+um2ZrOmBPEfFsXcaDzNpiFdAqgAWkKblETdF4VgyYbz8LFylorMWdvtq2kM7HuHToxdMzbpJIqHDQu7uScrZqvN3JEsr3mUt88SkZdIMB3OjaypIzruyenVoz6sgF3N8F2rJ16DMm/9zAb7WULXcAUeLfhJ0JJX0HGVVDaQ+0d/PbUWYCmJQAV8UKQqtaX1f3QIWkw0aQWwb9pObqPl5OFl5aSiXHN4E62vJEPIsAHxweaZ0jGPxzMnYdRI6sa6Cj2oag2sEAeNjgwfwQ8IHSHy/RJjuLljQGd7N9SdpMps6E=
